apiVersion: v1
kind: Service
metadata:
  name: imgvalidator
  namespace: imgvalidator
  labels:
    app: imgvalidator
spec:
  selector:
    app: imgvalidator
  ports:
    - protocol: TCP
      port: 1323
      targetPort: 1323